deploy:
    provider: firebase
    edge:
        branch: master
language: node_js
node_js:
    - "12"
before_install:
    - npm install -g firebase-tools
install:
    - yarn install
script:
    - npm test
    - npm run build
after_success:
    - firebase deploy --only hosting:admin-auction-finders-dev --token $FIREBASE_TOKEN
