language: node_js
node_js:
  - '12'
before_install:
  - npm install -g firebase-tools
install:
  - yarn install
script:
  - npm test
  - npm run build
  - firebase deploy --only hosting:admin-app --token $CI_TOKEN